name: ChainTests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  pytests:
    strategy:
      matrix:
        systems: [ "ubuntu-latest", "windows-latest" ]
        python-version: [3.8]

    runs-on: ${{ matrix.systems }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run testNode
      run:
        python -m unittest tests/testNode.py
    
    - name: Run testBlock
      run:
        python -m unittest tests/testBlock.py
